using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ArcheageBot
{
    class VisionHero
    {
        public static List<List<VisionForm>> HeroBars = new List<List<VisionForm>>();

        public static void LoadHeroBars()
        {
            /* Заливаем пиксели в переменные, так как форма имеет однообразный цвет */

            int ObjectMaxR = 70;
            int ObjectMinR = 35;
            int ObjectMaxG = 55;
            int ObjectMinG = 30;
            int ObjectMaxB = 30;
            int ObjectMinB = 15;

            int ManaBarMaxR = 50;
            int ManaBarMinR = 0;
            int ManaBarMaxG = 40;
            int ManaBarMinG = 0;
            int ManaBarMaxB = 30;
            int ManaBarMinB = 0;

            List<VisionForm> HeroBar1 = new List<VisionForm>
            {
                /* Определяем что нет буквы М */


                /* Полоска хп */
                new VisionForm(){
                    OffsetX = 1, 
                    OffsetY = 0, 
                    MaxR = ObjectMaxR,
                    MinR = ObjectMinR,
                    MaxG = ObjectMaxG,
                    MinG = ObjectMinG,
                    MaxB = ObjectMaxB,
                    MinB = ObjectMinB,
                    Object = true
                },
                new VisionForm(){
                    OffsetX = 2, 
                    OffsetY = 0, 
                    MaxR = ObjectMaxR,
                    MinR = ObjectMinR,
                    MaxG = ObjectMaxG,
                    MinG = ObjectMinG,
                    MaxB = ObjectMaxB,
                    MinB = ObjectMinB,
                    Object = true
                },
                new VisionForm(){
                    OffsetX = 3, 
                    OffsetY = 0, 
                    MaxR = ObjectMaxR,
                    MinR = ObjectMinR,
                    MaxG = ObjectMaxG,
                    MinG = ObjectMinG,
                    MaxB = ObjectMaxB,
                    MinB = ObjectMinB,
                    Object = true
                },
                new VisionForm(){
                    OffsetX = 4, 
                    OffsetY = 0, 
                    MaxR = ObjectMaxR,
                    MinR = ObjectMinR,
                    MaxG = ObjectMaxG,
                    MinG = ObjectMinG,
                    MaxB = ObjectMaxB,
                    MinB = ObjectMinB,
                    Object = true
                },
                new VisionForm(){
                    OffsetX = 5, 
                    OffsetY = 0, 
                    MaxR = ObjectMaxR,
                    MinR = ObjectMinR,
                    MaxG = ObjectMaxG,
                    MinG = ObjectMinG,
                    MaxB = ObjectMaxB,
                    MinB = ObjectMinB,
                    Object = true
                },
                new VisionForm(){
                    OffsetX = 6, 
                    OffsetY = 0, 
                    MaxR = ObjectMaxR,
                    MinR = ObjectMinR,
                    MaxG = ObjectMaxG,
                    MinG = ObjectMinG,
                    MaxB = ObjectMaxB,
                    MinB = ObjectMinB,
                    Object = true
                },
                new VisionForm(){
                    OffsetX = 7, 
                    OffsetY = 0, 
                    MaxR = ObjectMaxR,
                    MinR = ObjectMinR,
                    MaxG = ObjectMaxG,
                    MinG = ObjectMinG,
                    MaxB = ObjectMaxB,
                    MinB = ObjectMinB,
                    Object = true
                },
                new VisionForm(){
                    OffsetX = 8, 
                    OffsetY = 0, 
                    MaxR = ObjectMaxR,
                    MinR = ObjectMinR,
                    MaxG = ObjectMaxG,
                    MinG = ObjectMinG,
                    MaxB = ObjectMaxB,
                    MinB = ObjectMinB,
                    Object = true
                },
                new VisionForm(){
                    OffsetX = 9, 
                    OffsetY = 0, 
                    MaxR = ObjectMaxR,
                    MinR = ObjectMinR,
                    MaxG = ObjectMaxG,
                    MinG = ObjectMinG,
                    MaxB = ObjectMaxB,
                    MinB = ObjectMinB,
                    Object = true
                },
                new VisionForm(){
                    OffsetX = 10, 
                    OffsetY = 0, 
                    MaxR = ObjectMaxR,
                    MinR = ObjectMinR,
                    MaxG = ObjectMaxG,
                    MinG = ObjectMinG,
                    MaxB = ObjectMaxB,
                    MinB = ObjectMinB,
                    Object = true
                },
                new VisionForm(){
                    OffsetX = 11, 
                    OffsetY = 0, 
                    MaxR = ObjectMaxR,
                    MinR = ObjectMinR,
                    MaxG = ObjectMaxG,
                    MinG = ObjectMinG,
                    MaxB = ObjectMaxB,
                    MinB = ObjectMinB,
                    Object = true
                },
                new VisionForm(){
                    OffsetX = 12, 
                    OffsetY = 0, 
                    MaxR = ObjectMaxR,
                    MinR = ObjectMinR,
                    MaxG = ObjectMaxG,
                    MinG = ObjectMinG,
                    MaxB = ObjectMaxB,
                    MinB = ObjectMinB,
                    Object = true
                },
                new VisionForm(){
                    OffsetX = 13, 
                    OffsetY = 0, 
                    MaxR = ObjectMaxR,
                    MinR = ObjectMinR,
                    MaxG = ObjectMaxG,
                    MinG = ObjectMinG,
                    MaxB = ObjectMaxB,
                    MinB = ObjectMinB,
                    Object = true
                },
                new VisionForm(){
                    OffsetX = 14, 
                    OffsetY = 0, 
                    MaxR = ObjectMaxR,
                    MinR = ObjectMinR,
                    MaxG = ObjectMaxG,
                    MinG = ObjectMinG,
                    MaxB = ObjectMaxB,
                    MinB = ObjectMinB,
                    Object = true
                },
                new VisionForm(){
                    OffsetX = 15, 
                    OffsetY = 0, 
                    MaxR = ObjectMaxR,
                    MinR = ObjectMinR,
                    MaxG = ObjectMaxG,
                    MinG = ObjectMinG,
                    MaxB = ObjectMaxB,
                    MinB = ObjectMinB,
                    Object = true
                },
                new VisionForm(){
                    OffsetX = 16, 
                    OffsetY = 0, 
                    MaxR = ObjectMaxR,
                    MinR = ObjectMinR,
                    MaxG = ObjectMaxG,
                    MinG = ObjectMinG,
                    MaxB = ObjectMaxB,
                    MinB = ObjectMinB,
                    Object = true
                },
                new VisionForm(){
                    OffsetX = 17, 
                    OffsetY = 0, 
                    MaxR = ObjectMaxR,
                    MinR = ObjectMinR,
                    MaxG = ObjectMaxG,
                    MinG = ObjectMinG,
                    MaxB = ObjectMaxB,
                    MinB = ObjectMinB,
                    Object = true
                },
                new VisionForm(){
                    OffsetX = 18, 
                    OffsetY = 0, 
                    MaxR = ObjectMaxR,
                    MinR = ObjectMinR,
                    MaxG = ObjectMaxG,
                    MinG = ObjectMinG,
                    MaxB = ObjectMaxB,
                    MinB = ObjectMinB,
                    Object = true
                },
                new VisionForm(){
                    OffsetX = 19, 
                    OffsetY = 0, 
                    MaxR = ObjectMaxR,
                    MinR = ObjectMinR,
                    MaxG = ObjectMaxG,
                    MinG = ObjectMinG,
                    MaxB = ObjectMaxB,
                    MinB = ObjectMinB,
                    Object = true
                },
                new VisionForm(){
                    OffsetX = 20, 
                    OffsetY = 0, 
                    MaxR = ObjectMaxR,
                    MinR = ObjectMinR,
                    MaxG = ObjectMaxG,
                    MinG = ObjectMinG,
                    MaxB = ObjectMaxB,
                    MinB = ObjectMinB,
                    Object = true
                },
                new VisionForm(){
                    OffsetX = 21, 
                    OffsetY = 0, 
                    MaxR = ObjectMaxR,
                    MinR = ObjectMinR,
                    MaxG = ObjectMaxG,
                    MinG = ObjectMinG,
                    MaxB = ObjectMaxB,
                    MinB = ObjectMinB,
                    Object = true
                },
                new VisionForm(){
                    OffsetX = 22, 
                    OffsetY = 0, 
                    MaxR = ObjectMaxR,
                    MinR = ObjectMinR,
                    MaxG = ObjectMaxG,
                    MinG = ObjectMinG,
                    MaxB = ObjectMaxB,
                    MinB = ObjectMinB,
                    Object = true
                },
                new VisionForm(){
                    OffsetX = 23, 
                    OffsetY = 0, 
                    MaxR = ObjectMaxR,
                    MinR = ObjectMinR,
                    MaxG = ObjectMaxG,
                    MinG = ObjectMinG,
                    MaxB = ObjectMaxB,
                    MinB = ObjectMinB,
                    Object = true
                },
                new VisionForm(){
                    OffsetX = 24, 
                    OffsetY = 0, 
                    MaxR = ObjectMaxR,
                    MinR = ObjectMinR,
                    MaxG = ObjectMaxG,
                    MinG = ObjectMinG,
                    MaxB = ObjectMaxB,
                    MinB = ObjectMinB,
                    Object = true
                },
                new VisionForm(){
                    OffsetX = 25, 
                    OffsetY = 0, 
                    MaxR = ObjectMaxR,
                    MinR = ObjectMinR,
                    MaxG = ObjectMaxG,
                    MinG = ObjectMinG,
                    MaxB = ObjectMaxB,
                    MinB = ObjectMinB,
                    Object = true
                },
                new VisionForm(){
                    OffsetX = 26, 
                    OffsetY = 0, 
                    MaxR = ObjectMaxR,
                    MinR = ObjectMinR,
                    MaxG = ObjectMaxG,
                    MinG = ObjectMinG,
                    MaxB = ObjectMaxB,
                    MinB = ObjectMinB,
                    Object = true
                },
                new VisionForm(){
                    OffsetX = 27, 
                    OffsetY = 0, 
                    MaxR = ObjectMaxR,
                    MinR = ObjectMinR,
                    MaxG = ObjectMaxG,
                    MinG = ObjectMinG,
                    MaxB = ObjectMaxB,
                    MinB = ObjectMinB,
                    Object = true
                },
                new VisionForm(){
                    OffsetX = 28, 
                    OffsetY = 0, 
                    MaxR = ObjectMaxR,
                    MinR = ObjectMinR,
                    MaxG = ObjectMaxG,
                    MinG = ObjectMinG,
                    MaxB = ObjectMaxB,
                    MinB = ObjectMinB,
                    Object = true
                },
                new VisionForm(){
                    OffsetX = 29, 
                    OffsetY = 0, 
                    MaxR = ObjectMaxR,
                    MinR = ObjectMinR,
                    MaxG = ObjectMaxG,
                    MinG = ObjectMinG,
                    MaxB = ObjectMaxB,
                    MinB = ObjectMinB,
                    Object = true
                },
                new VisionForm(){
                    OffsetX = 30, 
                    OffsetY = 0, 
                    MaxR = ObjectMaxR,
                    MinR = ObjectMinR,
                    MaxG = ObjectMaxG,
                    MinG = ObjectMinG,
                    MaxB = ObjectMaxB,
                    MinB = ObjectMinB,
                    Object = true
                },
                new VisionForm(){
                    OffsetX = 31, 
                    OffsetY = 0, 
                    MaxR = ObjectMaxR,
                    MinR = ObjectMinR,
                    MaxG = ObjectMaxG,
                    MinG = ObjectMinG,
                    MaxB = ObjectMaxB,
                    MinB = ObjectMinB,
                    Object = true
                },
                new VisionForm(){
                    OffsetX = 32, 
                    OffsetY = 0, 
                    MaxR = ObjectMaxR,
                    MinR = ObjectMinR,
                    MaxG = ObjectMaxG,
                    MinG = ObjectMinG,
                    MaxB = ObjectMaxB,
                    MinB = ObjectMinB,
                    Object = true
                },
                new VisionForm(){
                    OffsetX = 33, 
                    OffsetY = 0, 
                    MaxR = ObjectMaxR,
                    MinR = ObjectMinR,
                    MaxG = ObjectMaxG,
                    MinG = ObjectMinG,
                    MaxB = ObjectMaxB,
                    MinB = ObjectMinB,
                    Object = true
                },
                new VisionForm(){
                    OffsetX = 34, 
                    OffsetY = 0, 
                    MaxR = ObjectMaxR,
                    MinR = ObjectMinR,
                    MaxG = ObjectMaxG,
                    MinG = ObjectMinG,
                    MaxB = ObjectMaxB,
                    MinB = ObjectMinB,
                    Object = true
                },
                new VisionForm(){
                    OffsetX = 35, 
                    OffsetY = 0, 
                    MaxR = ObjectMaxR,
                    MinR = ObjectMinR,
                    MaxG = ObjectMaxG,
                    MinG = ObjectMinG,
                    MaxB = ObjectMaxB,
                    MinB = ObjectMinB,
                    Object = true
                },
                new VisionForm(){
                    OffsetX = 36, 
                    OffsetY = 0, 
                    MaxR = ObjectMaxR,
                    MinR = ObjectMinR,
                    MaxG = ObjectMaxG,
                    MinG = ObjectMinG,
                    MaxB = ObjectMaxB,
                    MinB = ObjectMinB,
                    Object = true
                },
                new VisionForm(){
                    OffsetX = 37, 
                    OffsetY = 0, 
                    MaxR = ObjectMaxR,
                    MinR = ObjectMinR,
                    MaxG = ObjectMaxG,
                    MinG = ObjectMinG,
                    MaxB = ObjectMaxB,
                    MinB = ObjectMinB,
                    Object = true
                },
                new VisionForm(){
                    OffsetX = 38, 
                    OffsetY = 0, 
                    MaxR = ObjectMaxR,
                    MinR = ObjectMinR,
                    MaxG = ObjectMaxG,
                    MinG = ObjectMinG,
                    MaxB = ObjectMaxB,
                    MinB = ObjectMinB,
                    Object = true
                },
                new VisionForm(){
                    OffsetX = 39, 
                    OffsetY = 0, 
                    MaxR = ObjectMaxR,
                    MinR = ObjectMinR,
                    MaxG = ObjectMaxG,
                    MinG = ObjectMinG,
                    MaxB = ObjectMaxB,
                    MinB = ObjectMinB,
                    Object = true
                },
                new VisionForm(){
                    OffsetX = 40, 
                    OffsetY = 0, 
                    MaxR = ObjectMaxR,
                    MinR = ObjectMinR,
                    MaxG = ObjectMaxG,
                    MinG = ObjectMinG,
                    MaxB = ObjectMaxB,
                    MinB = ObjectMinB,
                    Object = true
                },
                new VisionForm(){
                    OffsetX = 41, 
                    OffsetY = 0, 
                    MaxR = ObjectMaxR,
                    MinR = ObjectMinR,
                    MaxG = ObjectMaxG,
                    MinG = ObjectMinG,
                    MaxB = ObjectMaxB,
                    MinB = ObjectMinB,
                    Object = true
                },
                new VisionForm(){
                    OffsetX = 42, 
                    OffsetY = 0, 
                    MaxR = ObjectMaxR,
                    MinR = ObjectMinR,
                    MaxG = ObjectMaxG,
                    MinG = ObjectMinG,
                    MaxB = ObjectMaxB,
                    MinB = ObjectMinB,
                    Object = true
                },
                new VisionForm(){
                    OffsetX = 43, 
                    OffsetY = 0, 
                    MaxR = ObjectMaxR,
                    MinR = ObjectMinR,
                    MaxG = ObjectMaxG,
                    MinG = ObjectMinG,
                    MaxB = ObjectMaxB,
                    MinB = ObjectMinB,
                    Object = true
                },
                new VisionForm(){
                    OffsetX = 44, 
                    OffsetY = 0, 
                    MaxR = ObjectMaxR,
                    MinR = ObjectMinR,
                    MaxG = ObjectMaxG,
                    MinG = ObjectMinG,
                    MaxB = ObjectMaxB,
                    MinB = ObjectMinB,
                    Object = true
                },
                new VisionForm(){
                    OffsetX = 45, 
                    OffsetY = 0, 
                    MaxR = ObjectMaxR,
                    MinR = ObjectMinR,
                    MaxG = ObjectMaxG,
                    MinG = ObjectMinG,
                    MaxB = ObjectMaxB,
                    MinB = ObjectMinB,
                    Object = true
                },
                new VisionForm(){
                    OffsetX = 46, 
                    OffsetY = 0, 
                    MaxR = ObjectMaxR,
                    MinR = ObjectMinR,
                    MaxG = ObjectMaxG,
                    MinG = ObjectMinG,
                    MaxB = ObjectMaxB,
                    MinB = ObjectMinB,
                    Object = true
                },
                new VisionForm(){
                    OffsetX = 47, 
                    OffsetY = 0, 
                    MaxR = ObjectMaxR,
                    MinR = ObjectMinR,
                    MaxG = ObjectMaxG,
                    MinG = ObjectMinG,
                    MaxB = ObjectMaxB,
                    MinB = ObjectMinB,
                    Object = true
                },
                new VisionForm(){
                    OffsetX = 48, 
                    OffsetY = 0, 
                    MaxR = ObjectMaxR,
                    MinR = ObjectMinR,
                    MaxG = ObjectMaxG,
                    MinG = ObjectMinG,
                    MaxB = ObjectMaxB,
                    MinB = ObjectMinB,
                    Object = true
                },
                new VisionForm(){
                    OffsetX = 49, 
                    OffsetY = 0, 
                    MaxR = ObjectMaxR,
                    MinR = ObjectMinR,
                    MaxG = ObjectMaxG,
                    MinG = ObjectMinG,
                    MaxB = ObjectMaxB,
                    MinB = ObjectMinB,
                    Object = true
                },
                new VisionForm(){
                    OffsetX = 50, 
                    OffsetY = 0, 
                    MaxR = ObjectMaxR,
                    MinR = ObjectMinR,
                    MaxG = ObjectMaxG,
                    MinG = ObjectMinG,
                    MaxB = ObjectMaxB,
                    MinB = ObjectMinB,
                    Object = true
                },
                new VisionForm(){
                    OffsetX = 51, 
                    OffsetY = 0, 
                    MaxR = ObjectMaxR,
                    MinR = ObjectMinR,
                    MaxG = ObjectMaxG,
                    MinG = ObjectMinG,
                    MaxB = ObjectMaxB,
                    MinB = ObjectMinB,
                    Object = true
                },
                new VisionForm(){
                    OffsetX = 52, 
                    OffsetY = 0, 
                    MaxR = ObjectMaxR,
                    MinR = ObjectMinR,
                    MaxG = ObjectMaxG,
                    MinG = ObjectMinG,
                    MaxB = ObjectMaxB,
                    MinB = ObjectMinB,
                    Object = true
                },
                new VisionForm(){
                    OffsetX = 53, 
                    OffsetY = 0, 
                    MaxR = ObjectMaxR,
                    MinR = ObjectMinR,
                    MaxG = ObjectMaxG,
                    MinG = ObjectMinG,
                    MaxB = ObjectMaxB,
                    MinB = ObjectMinB,
                    Object = true
                },
                new VisionForm(){
                    OffsetX = 54, 
                    OffsetY = 0, 
                    MaxR = ObjectMaxR,
                    MinR = ObjectMinR,
                    MaxG = ObjectMaxG,
                    MinG = ObjectMinG,
                    MaxB = ObjectMaxB,
                    MinB = ObjectMinB,
                    Object = true
                },
                new VisionForm(){
                    OffsetX = 55, 
                    OffsetY = 0, 
                    MaxR = ObjectMaxR,
                    MinR = ObjectMinR,
                    MaxG = ObjectMaxG,
                    MinG = ObjectMinG,
                    MaxB = ObjectMaxB,
                    MinB = ObjectMinB,
                    Object = true
                },
                new VisionForm(){
                    OffsetX = 56, 
                    OffsetY = 0, 
                    MaxR = ObjectMaxR,
                    MinR = ObjectMinR,
                    MaxG = ObjectMaxG,
                    MinG = ObjectMinG,
                    MaxB = ObjectMaxB,
                    MinB = ObjectMinB,
                    Object = true
                },
                new VisionForm(){
                    OffsetX = 57, 
                    OffsetY = 0, 
                    MaxR = ObjectMaxR,
                    MinR = ObjectMinR,
                    MaxG = ObjectMaxG,
                    MinG = ObjectMinG,
                    MaxB = ObjectMaxB,
                    MinB = ObjectMinB,
                    Object = true
                },
                new VisionForm(){
                    OffsetX = 58, 
                    OffsetY = 0, 
                    MaxR = ObjectMaxR,
                    MinR = ObjectMinR,
                    MaxG = ObjectMaxG,
                    MinG = ObjectMinG,
                    MaxB = ObjectMaxB,
                    MinB = ObjectMinB,
                    Object = true
                },
                new VisionForm(){
                    OffsetX = 59, 
                    OffsetY = 0, 
                    MaxR = ObjectMaxR,
                    MinR = ObjectMinR,
                    MaxG = ObjectMaxG,
                    MinG = ObjectMinG,
                    MaxB = ObjectMaxB,
                    MinB = ObjectMinB,
                    Object = true
                },
                new VisionForm(){
                    OffsetX = 60, 
                    OffsetY = 0, 
                    MaxR = ObjectMaxR,
                    MinR = ObjectMinR,
                    MaxG = ObjectMaxG,
                    MinG = ObjectMinG,
                    MaxB = ObjectMaxB,
                    MinB = ObjectMinB,
                    Object = true
                },
                new VisionForm(){
                    OffsetX = 61, 
                    OffsetY = 0, 
                    MaxR = ObjectMaxR,
                    MinR = ObjectMinR,
                    MaxG = ObjectMaxG,
                    MinG = ObjectMinG,
                    MaxB = ObjectMaxB,
                    MinB = ObjectMinB,
                    Object = true
                },
                new VisionForm(){
                    OffsetX = 62, 
                    OffsetY = 0, 
                    MaxR = ObjectMaxR,
                    MinR = ObjectMinR,
                    MaxG = ObjectMaxG,
                    MinG = ObjectMinG,
                    MaxB = ObjectMaxB,
                    MinB = ObjectMinB,
                    Object = true
                },
                new VisionForm(){
                    OffsetX = 63, 
                    OffsetY = 0, 
                    MaxR = ObjectMaxR,
                    MinR = ObjectMinR,
                    MaxG = ObjectMaxG,
                    MinG = ObjectMinG,
                    MaxB = ObjectMaxB,
                    MinB = ObjectMinB,
                    Object = true
                },
                new VisionForm(){
                    OffsetX = 64, 
                    OffsetY = 0, 
                    MaxR = ObjectMaxR,
                    MinR = ObjectMinR,
                    MaxG = ObjectMaxG,
                    MinG = ObjectMinG,
                    MaxB = ObjectMaxB,
                    MinB = ObjectMinB,
                    Object = true
                },
     new VisionForm(){
                    OffsetX = 10, 
                    OffsetY = 0, 
                    MaxR = ObjectMaxR,
                    MinR = ObjectMinR,
                    MaxG = ObjectMaxG,
                    MinG = ObjectMinG,
                    MaxB = ObjectMaxB,
                    MinB = ObjectMinB,
                    Object = true
                },
               
                new VisionForm(){
                    OffsetX = 30, 
                    OffsetY = 0, 
                    MaxR = ObjectMaxR,
                    MinR = ObjectMinR,
                    MaxG = ObjectMaxG,
                    MinG = ObjectMinG,
                    MaxB = ObjectMaxB,
                    MinB = ObjectMinB,
                    Object = true
                },
                new VisionForm(){
                    OffsetX = 40, 
                    OffsetY = 0, 
                    MaxR = ObjectMaxR,
                    MinR = ObjectMinR,
                    MaxG = ObjectMaxG,
                    MinG = ObjectMinG,
                    MaxB = ObjectMaxB,
                    MinB = ObjectMinB,
                    Object = true
                },
                new VisionForm(){
                    OffsetX = 50, 
                    OffsetY = 0, 
                    MaxR = ObjectMaxR,
                    MinR = ObjectMinR,
                    MaxG = ObjectMaxG,
                    MinG = ObjectMinG,
                    MaxB = ObjectMaxB,
                    MinB = ObjectMinB,
                    Object = true
                },
                new VisionForm(){
                    OffsetX = 60, 
                    OffsetY = 0, 
                    MaxR = ObjectMaxR,
                    MinR = ObjectMinR,
                    MaxG = ObjectMaxG,
                    MinG = ObjectMinG,
                    MaxB = ObjectMaxB,
                    MinB = ObjectMinB,
                    Object = true
                },
                new VisionForm(){
                    OffsetX = 70, 
                    OffsetY = 0, 
                    MaxR = ObjectMaxR,
                    MinR = ObjectMinR,
                    MaxG = ObjectMaxG,
                    MinG = ObjectMinG,
                    MaxB = ObjectMaxB,
                    MinB = ObjectMinB,
                    Object = true
                },
                new VisionForm(){
                    OffsetX = 80, 
                    OffsetY = 0, 
                    MaxR = ObjectMaxR,
                    MinR = ObjectMinR,
                    MaxG = ObjectMaxG,
                    MinG = ObjectMinG,
                    MaxB = ObjectMaxB,
                    MinB = ObjectMinB,
                    Object = true
                },
                new VisionForm(){
                    OffsetX = 90, 
                    OffsetY = 0, 
                    MaxR = ObjectMaxR,
                    MinR = ObjectMinR,
                    MaxG = ObjectMaxG,
                    MinG = ObjectMinG,
                    MaxB = ObjectMaxB,
                    MinB = ObjectMinB,
                    Object = true
                },
                new VisionForm(){
                    OffsetX = 100, 
                    OffsetY = 0, 
                    MaxR = ObjectMaxR,
                    MinR = ObjectMinR,
                    MaxG = ObjectMaxG,
                    MinG = ObjectMinG,
                    MaxB = ObjectMaxB,
                    MinB = ObjectMinB,
                    Object = true
                },
                new VisionForm(){
                    OffsetX = 110, 
                    OffsetY = 0, 
                    MaxR = ObjectMaxR,
                    MinR = ObjectMinR,
                    MaxG = ObjectMaxG,
                    MinG = ObjectMinG,
                    MaxB = ObjectMaxB,
                    MinB = ObjectMinB,
                    Object = true
                },
                new VisionForm(){
                    OffsetX = 120, 
                    OffsetY = 0, 
                    MaxR = ObjectMaxR,
                    MinR = ObjectMinR,
                    MaxG = ObjectMaxG,
                    MinG = ObjectMinG,
                    MaxB = ObjectMaxB,
                    MinB = ObjectMinB,
                    Object = true
                },
                new VisionForm(){
                    OffsetX = 128, 
                    OffsetY = 0, 
                    MaxR = ObjectMaxR,
                    MinR = ObjectMinR,
                    MaxG = ObjectMaxG,
                    MinG = ObjectMinG,
                    MaxB = ObjectMaxB,
                    MinB = ObjectMinB,
                    Object = true

                },
             
                new VisionForm(){
                    OffsetX = 130, 
                    OffsetY = 0, 
                    MaxR = ObjectMaxR,
                    MinR = ObjectMinR,
                    MaxG = ObjectMaxG,
                    MinG = ObjectMinG,
                    MaxB = ObjectMaxB,
                    MinB = ObjectMinB,
                    Object = true
                },
                new VisionForm(){
                    OffsetX = 150, 
                    OffsetY = 0, 
                    MaxR = ObjectMaxR,
                    MinR = ObjectMinR,
                    MaxG = ObjectMaxG,
                    MinG = ObjectMinG,
                    MaxB = ObjectMaxB,
                    MinB = ObjectMinB,
                    Object = true
                },
                new VisionForm(){
                    OffsetX = 160, 
                    OffsetY = 0, 
                    MaxR = ObjectMaxR,
                    MinR = ObjectMinR,
                    MaxG = ObjectMaxG,
                    MinG = ObjectMinG,
                    MaxB = ObjectMaxB,
                    MinB = ObjectMinB,
                    Object = true
                },
                new VisionForm(){
                    OffsetX = 170, 
                    OffsetY = 0, 
                    MaxR = ObjectMaxR,
                    MinR = ObjectMinR,
                    MaxG = ObjectMaxG,
                    MinG = ObjectMinG,
                    MaxB = ObjectMaxB,
                    MinB = ObjectMinB,
                    Object = true
                },
                new VisionForm(){
                    OffsetX = 180, 
                    OffsetY = 0, 
                    MaxR = ObjectMaxR,
                    MinR = ObjectMinR,
                    MaxG = ObjectMaxG,
                    MinG = ObjectMinG,
                    MaxB = ObjectMaxB,
                    MinB = ObjectMinB,
                    Object = true
                },
                new VisionForm(){
                    OffsetX = 190, 
                    OffsetY = 0, 
                    MaxR = ObjectMaxR,
                    MinR = ObjectMinR,
                    MaxG = ObjectMaxG,
                    MinG = ObjectMinG,
                    MaxB = ObjectMaxB,
                    MinB = ObjectMinB,
                    Object = true
                },
                new VisionForm(){
                    OffsetX = 200, 
                    OffsetY = 0, 
                    MaxR = ObjectMaxR,
                    MinR = ObjectMinR,
                    MaxG = ObjectMaxG,
                    MinG = ObjectMinG,
                    MaxB = ObjectMaxB,
                    MinB = ObjectMinB,
                    Object = true
                },
                new VisionForm(){
                    OffsetX = 210, 
                    OffsetY = 0, 
                    MaxR = ObjectMaxR,
                    MinR = ObjectMinR,
                    MaxG = ObjectMaxG,
                    MinG = ObjectMinG,
                    MaxB = ObjectMaxB,
                    MinB = ObjectMinB,
                    Object = true
                },
                new VisionForm(){
                    OffsetX = 220, 
                    OffsetY = 0, 
                    MaxR = ObjectMaxR,
                    MinR = ObjectMinR,
                    MaxG = ObjectMaxG,
                    MinG = ObjectMinG,
                    MaxB = ObjectMaxB,
                    MinB = ObjectMinB,
                    Object = true
                },
                new VisionForm(){
                    OffsetX = 230, 
                    OffsetY = 0, 
                    MaxR = ObjectMaxR,
                    MinR = ObjectMinR,
                    MaxG = ObjectMaxG,
                    MinG = ObjectMinG,
                    MaxB = ObjectMaxB,
                    MinB = ObjectMinB,
                    Object = true
                },
                new VisionForm(){
                    OffsetX = 235, 
                    OffsetY = 0, 
                    MaxR = ObjectMaxR,
                    MinR = ObjectMinR,
                    MaxG = ObjectMaxG,
                    MinG = ObjectMinG,
                    MaxB = ObjectMaxB,
                    MinB = ObjectMinB,
                    Object = true
                },
                new VisionForm(){
                    OffsetX = 240, 
                    OffsetY = 0, 
                    MaxR = ObjectMaxR,
                    MinR = ObjectMinR,
                    MaxG = ObjectMaxG,
                    MinG = ObjectMinG,
                    MaxB = ObjectMaxB,
                    MinB = ObjectMinB,
                    Object = true
                },
                new VisionForm(){
                    OffsetX = 241, 
                    OffsetY = 0, 
                    MaxR = ObjectMaxR,
                    MinR = ObjectMinR,
                    MaxG = ObjectMaxG,
                    MinG = ObjectMinG,
                    MaxB = ObjectMaxB,
                    MinB = ObjectMinB,
                    Object = true
                },
                new VisionForm(){
                    OffsetX = 242, 
                    OffsetY = 0, 
                    MaxR = ObjectMaxR,
                    MinR = ObjectMinR,
                    MaxG = ObjectMaxG,
                    MinG = ObjectMinG,
                    MaxB = ObjectMaxB,
                    MinB = ObjectMinB,
                    Object = true
                },
                new VisionForm(){
                    OffsetX = 243, 
                    OffsetY = 0, 
                    MaxR = ObjectMaxR,
                    MinR = ObjectMinR,
                    MaxG = ObjectMaxG,
                    MinG = ObjectMinG,
                    MaxB = ObjectMaxB,
                    MinB = ObjectMinB,
                    Object = true
                },
                new VisionForm(){
                    OffsetX = 244, 
                    OffsetY = 0, 
                    MaxR = ObjectMaxR,
                    MinR = ObjectMinR,
                    MaxG = ObjectMaxG,
                    MinG = ObjectMinG,
                    MaxB = ObjectMaxB,
                    MinB = ObjectMinB,
                    Object = true
                },
                new VisionForm(){
                    OffsetX = 245, 
                    OffsetY = 0, 
                    MaxR = ObjectMaxR,
                    MinR = ObjectMinR,
                    MaxG = ObjectMaxG,
                    MinG = ObjectMinG,
                    MaxB = ObjectMaxB,
                    MinB = ObjectMinB,
                    Object = true
                },
                new VisionForm(){
                    OffsetX = 246, 
                    OffsetY = 0, 
                    MaxR = ObjectMaxR,
                    MinR = ObjectMinR,
                    MaxG = ObjectMaxG,
                    MinG = ObjectMinG,
                    MaxB = ObjectMaxB,
                    MinB = ObjectMinB,
                    Object = true
                },
                new VisionForm(){
                    OffsetX = 247, 
                    OffsetY = 0, 
                    MaxR = ObjectMaxR,
                    MinR = ObjectMinR,
                    MaxG = ObjectMaxG,
                    MinG = ObjectMinG,
                    MaxB = ObjectMaxB,
                    MinB = ObjectMinB,
                    Object = true
                },
                new VisionForm(){
                    OffsetX = 248, 
                    OffsetY = 0, 
                    MaxR = ObjectMaxR,
                    MinR = ObjectMinR,
                    MaxG = ObjectMaxG,
                    MinG = ObjectMinG,
                    MaxB = ObjectMaxB,
                    MinB = ObjectMinB,
                    Object = true
                },
                new VisionForm(){
                    OffsetX = 249, 
                    OffsetY = 0, 
                    MaxR = ObjectMaxR,
                    MinR = ObjectMinR,
                    MaxG = ObjectMaxG,
                    MinG = ObjectMinG,
                    MaxB = ObjectMaxB,
                    MinB = ObjectMinB,
                    Object = true

                },
                new VisionForm(){
                    OffsetX = 250, 
                    OffsetY = 0, 
                    MaxR = ObjectMaxR,
                    MinR = ObjectMinR,
                    MaxG = ObjectMaxG,
                    MinG = ObjectMinG,
                    MaxB = ObjectMaxB,
                    MinB = ObjectMinB,
                    Object = true
                },


                                                            /* Полоса хп над маной */
                new VisionForm(){
                    OffsetX = 1, 
                    OffsetY = 17, 
                    MaxR = ManaBarMaxR,
                    MinR = ManaBarMinR,
                    MaxG = ManaBarMaxG,
                    MinG = ManaBarMinG,
                    MaxB = ManaBarMaxB,
                    MinB = ManaBarMinB,
                },
                new VisionForm(){
                    OffsetX = 2, 
                    OffsetY = 17, 
                    MaxR = ManaBarMaxR,
                    MinR = ManaBarMinR,
                    MaxG = ManaBarMaxG,
                    MinG = ManaBarMinG,
                    MaxB = ManaBarMaxB,
                    MinB = ManaBarMinB,
                },
                new VisionForm(){
                    OffsetX = 3, 
                    OffsetY = 17, 
                    MaxR = ManaBarMaxR,
                    MinR = ManaBarMinR,
                    MaxG = ManaBarMaxG,
                    MinG = ManaBarMinG,
                    MaxB = ManaBarMaxB,
                    MinB = ManaBarMinB,
                },
                new VisionForm(){
                    OffsetX = 4, 
                    OffsetY = 17, 
                    MaxR = ManaBarMaxR,
                    MinR = ManaBarMinR,
                    MaxG = ManaBarMaxG,
                    MinG = ManaBarMinG,
                    MaxB = ManaBarMaxB,
                    MinB = ManaBarMinB,
                },
                new VisionForm(){
                    OffsetX = 5, 
                    OffsetY = 17, 
                    MaxR = ManaBarMaxR,
                    MinR = ManaBarMinR,
                    MaxG = ManaBarMaxG,
                    MinG = ManaBarMinG,
                    MaxB = ManaBarMaxB,
                    MinB = ManaBarMinB,
                },
                new VisionForm(){
                    OffsetX = 6, 
                    OffsetY = 17, 
                    MaxR = ManaBarMaxR,
                    MinR = ManaBarMinR,
                    MaxG = ManaBarMaxG,
                    MinG = ManaBarMinG,
                    MaxB = ManaBarMaxB,
                    MinB = ManaBarMinB,
                },
                new VisionForm(){
                    OffsetX = 7, 
                    OffsetY = 17, 
                    MaxR = ManaBarMaxR,
                    MinR = ManaBarMinR,
                    MaxG = ManaBarMaxG,
                    MinG = ManaBarMinG,
                    MaxB = ManaBarMaxB,
                    MinB = ManaBarMinB,
                },
                new VisionForm(){
                    OffsetX = 8, 
                    OffsetY = 17, 
                    MaxR = ManaBarMaxR,
                    MinR = ManaBarMinR,
                    MaxG = ManaBarMaxG,
                    MinG = ManaBarMinG,
                    MaxB = ManaBarMaxB,
                    MinB = ManaBarMinB,
                },
                 new VisionForm(){
                    OffsetX = 9, 
                    OffsetY = 17, 
                    MaxR = ManaBarMaxR,
                    MinR = ManaBarMinR,
                    MaxG = ManaBarMaxG,
                    MinG = ManaBarMinG,
                    MaxB = ManaBarMaxB,
                    MinB = ManaBarMinB,
                },
                 new VisionForm(){
                    OffsetX = 10, 
                    OffsetY = 17, 
                    MaxR = ManaBarMaxR,
                    MinR = ManaBarMinR,
                    MaxG = ManaBarMaxG,
                    MinG = ManaBarMinG,
                    MaxB = ManaBarMaxB,
                    MinB = ManaBarMinB,
                },
                 new VisionForm(){
                    OffsetX = 11, 
                    OffsetY = 17, 
                    MaxR = ManaBarMaxR,
                    MinR = ManaBarMinR,
                    MaxG = ManaBarMaxG,
                    MinG = ManaBarMinG,
                    MaxB = ManaBarMaxB,
                    MinB = ManaBarMinB,
                },
                 new VisionForm(){
                    OffsetX = 12, 
                    OffsetY = 17, 
                    MaxR = ManaBarMaxR,
                    MinR = ManaBarMinR,
                    MaxG = ManaBarMaxG,
                    MinG = ManaBarMinG,
                    MaxB = ManaBarMaxB,
                    MinB = ManaBarMinB,
                },
                 new VisionForm(){
                    OffsetX = 13, 
                    OffsetY = 17, 
                    MaxR = ManaBarMaxR,
                    MinR = ManaBarMinR,
                    MaxG = ManaBarMaxG,
                    MinG = ManaBarMinG,
                    MaxB = ManaBarMaxB,
                    MinB = ManaBarMinB,
                },
                 new VisionForm(){
                    OffsetX = 14, 
                    OffsetY = 17, 
                    MaxR = ManaBarMaxR,
                    MinR = ManaBarMinR,
                    MaxG = ManaBarMaxG,
                    MinG = ManaBarMinG,
                    MaxB = ManaBarMaxB,
                    MinB = ManaBarMinB,
                },
                 new VisionForm(){
                    OffsetX = 15, 
                    OffsetY = 17, 
                    MaxR = ManaBarMaxR,
                    MinR = ManaBarMinR,
                    MaxG = ManaBarMaxG,
                    MinG = ManaBarMinG,
                    MaxB = ManaBarMaxB,
                    MinB = ManaBarMinB,
                },
                 new VisionForm(){
                    OffsetX = 17, 
                    OffsetY = 17, 
                    MaxR = ManaBarMaxR,
                    MinR = ManaBarMinR,
                    MaxG = ManaBarMaxG,
                    MinG = ManaBarMinG,
                    MaxB = ManaBarMaxB,
                    MinB = ManaBarMinB,
                },
                new VisionForm(){
                    OffsetX = 16, 
                    OffsetY = 17, 
                    MaxR = ManaBarMaxR,
                    MinR = ManaBarMinR,
                    MaxG = ManaBarMaxG,
                    MinG = ManaBarMinG,
                    MaxB = ManaBarMaxB,
                    MinB = ManaBarMinB,
                },
                 new VisionForm(){
                    OffsetX = 18, 
                    OffsetY = 17, 
                    MaxR = ManaBarMaxR,
                    MinR = ManaBarMinR,
                    MaxG = ManaBarMaxG,
                    MinG = ManaBarMinG,
                    MaxB = ManaBarMaxB,
                    MinB = ManaBarMinB,
                },
                 new VisionForm(){
                    OffsetX = 19, 
                    OffsetY = 17, 
                    MaxR = ManaBarMaxR,
                    MinR = ManaBarMinR,
                    MaxG = ManaBarMaxG,
                    MinG = ManaBarMinG,
                    MaxB = ManaBarMaxB,
                    MinB = ManaBarMinB,
                },
                 new VisionForm(){
                    OffsetX = 20, 
                    OffsetY = 17, 
                    MaxR = ManaBarMaxR,
                    MinR = ManaBarMinR,
                    MaxG = ManaBarMaxG,
                    MinG = ManaBarMinG,
                    MaxB = ManaBarMaxB,
                    MinB = ManaBarMinB,
                },
                 new VisionForm(){
                    OffsetX = 21, 
                    OffsetY = 17, 
                    MaxR = ManaBarMaxR,
                    MinR = ManaBarMinR,
                    MaxG = ManaBarMaxG,
                    MinG = ManaBarMinG,
                    MaxB = ManaBarMaxB,
                    MinB = ManaBarMinB,
                },
                 new VisionForm(){
                    OffsetX = 22, 
                    OffsetY = 17, 
                    MaxR = ManaBarMaxR,
                    MinR = ManaBarMinR,
                    MaxG = ManaBarMaxG,
                    MinG = ManaBarMinG,
                    MaxB = ManaBarMaxB,
                    MinB = ManaBarMinB,
                },
                 new VisionForm(){
                    OffsetX = 23, 
                    OffsetY = 17, 
                    MaxR = ManaBarMaxR,
                    MinR = ManaBarMinR,
                    MaxG = ManaBarMaxG,
                    MinG = ManaBarMinG,
                    MaxB = ManaBarMaxB,
                    MinB = ManaBarMinB,
                },
                 new VisionForm(){
                    OffsetX = 24, 
                    OffsetY = 17, 
                    MaxR = ManaBarMaxR,
                    MinR = ManaBarMinR,
                    MaxG = ManaBarMaxG,
                    MinG = ManaBarMinG,
                    MaxB = ManaBarMaxB,
                    MinB = ManaBarMinB,
                },
                 new VisionForm(){
                    OffsetX = 25, 
                    OffsetY = 17, 
                    MaxR = ManaBarMaxR,
                    MinR = ManaBarMinR,
                    MaxG = ManaBarMaxG,
                    MinG = ManaBarMinG,
                    MaxB = ManaBarMaxB,
                    MinB = ManaBarMinB,
                },
                 new VisionForm(){
                    OffsetX = 26, 
                    OffsetY = 17, 
                    MaxR = ManaBarMaxR,
                    MinR = ManaBarMinR,
                    MaxG = ManaBarMaxG,
                    MinG = ManaBarMinG,
                    MaxB = ManaBarMaxB,
                    MinB = ManaBarMinB,
                },
                 new VisionForm(){
                    OffsetX = 27, 
                    OffsetY = 17, 
                    MaxR = ManaBarMaxR,
                    MinR = ManaBarMinR,
                    MaxG = ManaBarMaxG,
                    MinG = ManaBarMinG,
                    MaxB = ManaBarMaxB,
                    MinB = ManaBarMinB,
                },
                 new VisionForm(){
                    OffsetX = 28, 
                    OffsetY = 17, 
                    MaxR = ManaBarMaxR,
                    MinR = ManaBarMinR,
                    MaxG = ManaBarMaxG,
                    MinG = ManaBarMinG,
                    MaxB = ManaBarMaxB,
                    MinB = ManaBarMinB,
                },
                 new VisionForm(){
                    OffsetX = 29, 
                    OffsetY = 17, 
                    MaxR = ManaBarMaxR,
                    MinR = ManaBarMinR,
                    MaxG = ManaBarMaxG,
                    MinG = ManaBarMinG,
                    MaxB = ManaBarMaxB,
                    MinB = ManaBarMinB,
                },
                 new VisionForm(){
                    OffsetX = 30, 
                    OffsetY = 17, 
                    MaxR = ManaBarMaxR,
                    MinR = ManaBarMinR,
                    MaxG = ManaBarMaxG,
                    MinG = ManaBarMinG,
                    MaxB = ManaBarMaxB,
                    MinB = ManaBarMinB,
                },
                 new VisionForm(){
                    OffsetX = 31, 
                    OffsetY = 17, 
                    MaxR = ManaBarMaxR,
                    MinR = ManaBarMinR,
                    MaxG = ManaBarMaxG,
                    MinG = ManaBarMinG,
                    MaxB = ManaBarMaxB,
                    MinB = ManaBarMinB,
                },
                new VisionForm(){
                    OffsetX = 32, 
                    OffsetY = 17, 
                    MaxR = ManaBarMaxR,
                    MinR = ManaBarMinR,
                    MaxG = ManaBarMaxG,
                    MinG = ManaBarMinG,
                    MaxB = ManaBarMaxB,
                    MinB = ManaBarMinB,
                },
                new VisionForm(){
                    OffsetX = 64, 
                    OffsetY = 17, 
                    MaxR = ManaBarMaxR,
                    MinR = ManaBarMinR,
                    MaxG = ManaBarMaxG,
                    MinG = ManaBarMinG,
                    MaxB = ManaBarMaxB,
                    MinB = ManaBarMinB,
                },
                    new VisionForm(){
                    OffsetX = 10, 
                    OffsetY = 17, 
                    MaxR = ManaBarMaxR,
                    MinR = ManaBarMinR,
                    MaxG = ManaBarMaxG,
                    MinG = ManaBarMinG,
                    MaxB = ManaBarMaxB,
                    MinB = ManaBarMinB,
                },
                new VisionForm(){
                    OffsetX = 20, 
                    OffsetY = 17, 
                    MaxR = ManaBarMaxR,
                    MinR = ManaBarMinR,
                    MaxG = ManaBarMaxG,
                    MinG = ManaBarMinG,
                    MaxB = ManaBarMaxB,
                    MinB = ManaBarMinB,
                },
                new VisionForm(){
                    OffsetX = 30, 
                    OffsetY = 17, 
                    MaxR = ManaBarMaxR,
                    MinR = ManaBarMinR,
                    MaxG = ManaBarMaxG,
                    MinG = ManaBarMinG,
                    MaxB = ManaBarMaxB,
                    MinB = ManaBarMinB,
                },
                new VisionForm(){
                    OffsetX = 40, 
                    OffsetY = 17, 
                    MaxR = ManaBarMaxR,
                    MinR = ManaBarMinR,
                    MaxG = ManaBarMaxG,
                    MinG = ManaBarMinG,
                    MaxB = ManaBarMaxB,
                    MinB = ManaBarMinB,
                },
                new VisionForm(){
                    OffsetX = 50, 
                    OffsetY = 17, 
                    MaxR = ManaBarMaxR,
                    MinR = ManaBarMinR,
                    MaxG = ManaBarMaxG,
                    MinG = ManaBarMinG,
                    MaxB = ManaBarMaxB,
                    MinB = ManaBarMinB,
                },
                new VisionForm(){
                    OffsetX = 60, 
                    OffsetY = 17, 
                    MaxR = ManaBarMaxR,
                    MinR = ManaBarMinR,
                    MaxG = ManaBarMaxG,
                    MinG = ManaBarMinG,
                    MaxB = ManaBarMaxB,
                    MinB = ManaBarMinB,
                },
                new VisionForm(){
                    OffsetX = 70, 
                    OffsetY = 17, 
                    MaxR = ManaBarMaxR,
                    MinR = ManaBarMinR,
                    MaxG = ManaBarMaxG,
                    MinG = ManaBarMinG,
                    MaxB = ManaBarMaxB,
                    MinB = ManaBarMinB,
                },
                new VisionForm(){
                    OffsetX = 80, 
                    OffsetY = 17, 
                    MaxR = ManaBarMaxR,
                    MinR = ManaBarMinR,
                    MaxG = ManaBarMaxG,
                    MinG = ManaBarMinG,
                    MaxB = ManaBarMaxB,
                    MinB = ManaBarMinB,
                },
                new VisionForm(){
                    OffsetX = 90, 
                    OffsetY = 17, 
                    MaxR = ManaBarMaxR,
                    MinR = ManaBarMinR,
                    MaxG = ManaBarMaxG,
                    MinG = ManaBarMinG,
                    MaxB = ManaBarMaxB,
                    MinB = ManaBarMinB,
                },
                new VisionForm(){
                    OffsetX = 100, 
                    OffsetY = 17, 
                    MaxR = ManaBarMaxR,
                    MinR = ManaBarMinR,
                    MaxG = ManaBarMaxG,
                    MinG = ManaBarMinG,
                    MaxB = ManaBarMaxB,
                    MinB = ManaBarMinB,
                },
                new VisionForm(){
                    OffsetX = 110, 
                    OffsetY = 17, 
                    MaxR = ManaBarMaxR,
                    MinR = ManaBarMinR,
                    MaxG = ManaBarMaxG,
                    MinG = ManaBarMinG,
                    MaxB = ManaBarMaxB,
                    MinB = ManaBarMinB,
                },
                new VisionForm(){
                    OffsetX = 128, 
                    OffsetY = 17, 
                    MaxR = ManaBarMaxR,
                    MinR = ManaBarMinR,
                    MaxG = ManaBarMaxG,
                    MinG = ManaBarMinG,
                    MaxB = ManaBarMaxB,
                    MinB = ManaBarMinB,
                },
              new VisionForm(){
                    OffsetX = 120, 
                    OffsetY = 17, 
                    MaxR = ManaBarMaxR,
                    MinR = ManaBarMinR,
                    MaxG = ManaBarMaxG,
                    MinG = ManaBarMinG,
                    MaxB = ManaBarMaxB,
                    MinB = ManaBarMinB,
                },
                new VisionForm(){
                    OffsetX = 130, 
                    OffsetY = 17, 
                    MaxR = ManaBarMaxR,
                    MinR = ManaBarMinR,
                    MaxG = ManaBarMaxG,
                    MinG = ManaBarMinG,
                    MaxB = ManaBarMaxB,
                    MinB = ManaBarMinB,
                },
                new VisionForm(){
                    OffsetX = 140, 
                    OffsetY = 17, 
                    MaxR = ManaBarMaxR,
                    MinR = ManaBarMinR,
                    MaxG = ManaBarMaxG,
                    MinG = ManaBarMinG,
                    MaxB = ManaBarMaxB,
                    MinB = ManaBarMinB,
                },
                new VisionForm(){
                    OffsetX = 150, 
                    OffsetY = 17, 
                    MaxR = ManaBarMaxR,
                    MinR = ManaBarMinR,
                    MaxG = ManaBarMaxG,
                    MinG = ManaBarMinG,
                    MaxB = ManaBarMaxB,
                    MinB = ManaBarMinB,
                },
                new VisionForm(){
                    OffsetX = 160, 
                    OffsetY = 17, 
                    MaxR = ManaBarMaxR,
                    MinR = ManaBarMinR,
                    MaxG = ManaBarMaxG,
                    MinG = ManaBarMinG,
                    MaxB = ManaBarMaxB,
                    MinB = ManaBarMinB,
                },
                new VisionForm(){
                    OffsetX = 170, 
                    OffsetY = 17, 
                    MaxR = ManaBarMaxR,
                    MinR = ManaBarMinR,
                    MaxG = ManaBarMaxG,
                    MinG = ManaBarMinG,
                    MaxB = ManaBarMaxB,
                    MinB = ManaBarMinB,
                },
                new VisionForm(){
                    OffsetX = 180, 
                    OffsetY = 17, 
                    MaxR = ManaBarMaxR,
                    MinR = ManaBarMinR,
                    MaxG = ManaBarMaxG,
                    MinG = ManaBarMinG,
                    MaxB = ManaBarMaxB,
                    MinB = ManaBarMinB,
                },
                new VisionForm(){
                    OffsetX = 190, 
                    OffsetY = 17, 
                    MaxR = ManaBarMaxR,
                    MinR = ManaBarMinR,
                    MaxG = ManaBarMaxG,
                    MinG = ManaBarMinG,
                    MaxB = ManaBarMaxB,
                    MinB = ManaBarMinB,
                },
                new VisionForm(){
                    OffsetX = 200, 
                    OffsetY = 17, 
                    MaxR = ManaBarMaxR,
                    MinR = ManaBarMinR,
                    MaxG = ManaBarMaxG,
                    MinG = ManaBarMinG,
                    MaxB = ManaBarMaxB,
                    MinB = ManaBarMinB,
                },
                new VisionForm(){
                    OffsetX = 210, 
                    OffsetY = 17, 
                    MaxR = ManaBarMaxR,
                    MinR = ManaBarMinR,
                    MaxG = ManaBarMaxG,
                    MinG = ManaBarMinG,
                    MaxB = ManaBarMaxB,
                    MinB = ManaBarMinB,
                },
                new VisionForm(){
                    OffsetX = 220, 
                    OffsetY = 17, 
                    MaxR = ManaBarMaxR,
                    MinR = ManaBarMinR,
                    MaxG = ManaBarMaxG,
                    MinG = ManaBarMinG,
                    MaxB = ManaBarMaxB,
                    MinB = ManaBarMinB,
                },
                new VisionForm(){
                    OffsetX = 230, 
                    OffsetY = 17, 
                    MaxR = ManaBarMaxR,
                    MinR = ManaBarMinR,
                    MaxG = ManaBarMaxG,
                    MinG = ManaBarMinG,
                    MaxB = ManaBarMaxB,
                    MinB = ManaBarMinB,
                },
                new VisionForm(){
                    OffsetX = 240, 
                    OffsetY = 17, 
                    MaxR = ManaBarMaxR,
                    MinR = ManaBarMinR,
                    MaxG = ManaBarMaxG,
                    MinG = ManaBarMinG,
                    MaxB = ManaBarMaxB,
                    MinB = ManaBarMinB,
                },
                new VisionForm(){
                    OffsetX = 241, 
                    OffsetY = 17, 
                    MaxR = ManaBarMaxR,
                    MinR = ManaBarMinR,
                    MaxG = ManaBarMaxG,
                    MinG = ManaBarMinG,
                    MaxB = ManaBarMaxB,
                    MinB = ManaBarMinB,
                },
                new VisionForm(){
                    OffsetX = 242, 
                    OffsetY = 17, 
                    MaxR = ManaBarMaxR,
                    MinR = ManaBarMinR,
                    MaxG = ManaBarMaxG,
                    MinG = ManaBarMinG,
                    MaxB = ManaBarMaxB,
                    MinB = ManaBarMinB,
                },
                new VisionForm(){
                    OffsetX = 243, 
                    OffsetY = 17, 
                    MaxR = ManaBarMaxR,
                    MinR = ManaBarMinR,
                    MaxG = ManaBarMaxG,
                    MinG = ManaBarMinG,
                    MaxB = ManaBarMaxB,
                    MinB = ManaBarMinB,
                },
                new VisionForm(){
                    OffsetX = 244, 
                    OffsetY = 17, 
                    MaxR = ManaBarMaxR,
                    MinR = ManaBarMinR,
                    MaxG = ManaBarMaxG,
                    MinG = ManaBarMinG,
                    MaxB = ManaBarMaxB,
                    MinB = ManaBarMinB,
                },
                new VisionForm(){
                    OffsetX = 245, 
                    OffsetY = 17, 
                    MaxR = ManaBarMaxR,
                    MinR = ManaBarMinR,
                    MaxG = ManaBarMaxG,
                    MinG = ManaBarMinG,
                    MaxB = ManaBarMaxB,
                    MinB = ManaBarMinB,
                },
                new VisionForm(){
                    OffsetX = 246, 
                    OffsetY = 17, 
                    MaxR = ManaBarMaxR,
                    MinR = ManaBarMinR,
                    MaxG = ManaBarMaxG,
                    MinG = ManaBarMinG,
                    MaxB = ManaBarMaxB,
                    MinB = ManaBarMinB,
                },
                new VisionForm(){
                    OffsetX = 247, 
                    OffsetY = 17, 
                    MaxR = ManaBarMaxR,
                    MinR = ManaBarMinR,
                    MaxG = ManaBarMaxG,
                    MinG = ManaBarMinG,
                    MaxB = ManaBarMaxB,
                    MinB = ManaBarMinB,
                },
                new VisionForm(){
                    OffsetX = 248, 
                    OffsetY = 17, 
                    MaxR = ManaBarMaxR,
                    MinR = ManaBarMinR,
                    MaxG = ManaBarMaxG,
                    MinG = ManaBarMinG,
                    MaxB = ManaBarMaxB,
                    MinB = ManaBarMinB,
                },
                new VisionForm(){
                    OffsetX = 249, 
                    OffsetY = 17, 
                    MaxR = ManaBarMaxR,
                    MinR = ManaBarMinR,
                    MaxG = ManaBarMaxG,
                    MinG = ManaBarMinG,
                    MaxB = ManaBarMaxB,
                    MinB = ManaBarMinB,
                },
                new VisionForm(){
                    OffsetX = 250, 
                    OffsetY = 17, 
                    MaxR = ManaBarMaxR,
                    MinR = ManaBarMinR,
                    MaxG = ManaBarMaxG,
                    MinG = ManaBarMinG,
                    MaxB = ManaBarMaxB,
                    MinB = ManaBarMinB,
                },

            };

            VisionHero.HeroBars.Add(HeroBar1);

        }
    }
}
